/**
 * Copyright (c) Microsoft Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { describe, expect, it, vi } from 'vitest';
import formTools from '../src/tools/form.js';
import { Response } from '../src/response.js';
import type { Context } from '../src/context.js';
import type { Tab } from '../src/tab.js';

function setup(actions: { setChecked?: (checked: boolean) => Promise<void>, selectOption?: (option: string | { label: string }) => Promise<void> }) {
  const locator = {
    normalize: async () => ({ toString: () => "getByLabel('Field')" }),
    ...actions,
  };
  // SAFETY: form handlers use only modalStates and refLocator on this tab.
  const tab = { modalStates: () => [], refLocator: vi.fn().mockResolvedValue(locator) } as Tab;
  // SAFETY: the form handler and Response.code use only this context's current tab.
  const context = { currentTabOrDie: () => tab } as Context;
  const response = new Response(context, 'browser_fill_form', {});
  return { context, response, page: { getByLabel: () => locator } };
}

async function replay(response: Response, page: ReturnType<typeof setup>['page']) {
  // SAFETY: the snippet is generated by the form tool from fixed templates and quoted text.
  await new Function('page', `return (async () => { ${response.code()} })();`)(page);
}

describe('form tool generated-code replay', () => {
  it.each([
    ['checkbox', true], ['checkbox', false], ['radio', true], ['radio', false],
  ] as const)('replays %s checked=%s as a boolean', async (type, expected) => {
    let checked = !expected;
    const { context, response, page } = setup({ setChecked: async value => {
      if (typeof value !== 'boolean')
        throw new TypeError('checked must be a boolean');
      checked = value;
    } });
    await formTools[0].handle(context, { fields: [{ name: 'Field', ref: 'e1', type, value: String(expected) }] }, response);
    expect(checked).toBe(expected);
    checked = !expected;
    await replay(response, page);
    expect(checked).toBe(expected);
  });

  it.each(['Preferred', `Owner's "choice"\nline`])('replays label-only selection for %j', async label => {
    const options = [
      { value: label, label: 'Wrong option' },
      { value: 'correct-value', label },
    ];
    let selected = '';
    const { context, response, page } = setup({ selectOption: async option => {
      const found = options.find(candidate => typeof option === 'string'
        ? candidate.value === option || candidate.label === option
        : candidate.label === option.label);
      if (!found)
        throw new Error('Option not found');
      selected = found.value;
    } });
    await formTools[0].handle(context, { fields: [{ name: 'Field', ref: 'e1', type: 'combobox', value: label }] }, response);
    expect(selected).toBe('correct-value');
    selected = '';
    await replay(response, page);
    expect(selected).toBe('correct-value');
  });
});
